// This file is automatically generated. Do not modify it manually.
// To regenerate this file, run the "Request Firebase config" action.
const firebaseConfig = {
  "projectId": "studio-9235327350-ef1fc",
  "appId": "1:117593532807:web:aca2c88165009852c10b22",
  "apiKey": "AIzaSyAgIQTwEsewD5BVdDK8XaNAAGPAZ3YZAj8",
  "authDomain": "studio-9235327350-ef1fc.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "117593532807",
  "storageBucket": "studio-9235327350-ef1fc.appspot.com"
};
export default firebaseConfig;
